/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        tertiary: "#566445",
        secondary: "#526074",
        "surface-container-lowest": "#ffffff",
        surface: "#f7f9fb",
        background: "#f7f9fb",
        "on-surface": "#2a3439",
        "secondary-fixed": "#d5e3fc",
        "surface-container-high": "#e1e9ee",
        "on-tertiary-fixed-variant": "#596748",
        "inverse-primary": "#b8f9de",
        "primary-dim": "#1d5d49",
        "error-container": "#fe8983",
        "surface-tint": "#2b6954",
        "secondary-dim": "#465468",
        "on-primary-fixed": "#004936",
        "on-secondary-fixed": "#324053",
        "tertiary-dim": "#4a5739",
        "on-background": "#2a3439",
        error: "#9f403d",
        "surface-container": "#e8eff3",
        "on-primary-container": "#1c5c48",
        "tertiary-fixed-dim": "#d6e5be",
        "surface-variant": "#d9e4ea",
        "primary-fixed": "#b0f0d6",
        "secondary-container": "#d5e3fc",
        "outline-variant": "#a9b4b9",
        "on-error-container": "#752121",
        "tertiary-fixed": "#e4f4cc",
        "error-dim": "#4e0309",
        "primary-container": "#b0f0d6",
        primary: "#2b6954",
        "inverse-surface": "#0b0f10",
        "inverse-on-surface": "#9a9d9f",
        "on-tertiary": "#efffd6",
        "on-error": "#fff7f6",
        "on-tertiary-container": "#4f5d3e",
        "on-secondary": "#f8f8ff",
        "on-secondary-fixed-variant": "#4e5c71",
        "surface-container-low": "#f0f4f7",
        "on-surface-variant": "#566166",
        "surface-dim": "#cfdce3",
        outline: "#717c82",
        "on-primary": "#dffff0",
        "on-tertiary-fixed": "#3d4a2e",
        "secondary-fixed-dim": "#c7d5ed",
        "surface-container-highest": "#d9e4ea",
        "on-primary-fixed-variant": "#286652",
        "tertiary-container": "#e4f4cc",
        "on-secondary-container": "#455367",
        "surface-bright": "#f7f9fb",
        "primary-fixed-dim": "#a2e2c8",
      },
      fontFamily: {
        headline: ["Manrope"],
        body: ["Inter"],
        label: ["Inter"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
