-- Supabase / Postgres migration: fee_categories + optional auto-pricing filter columns
-- Safe to run multiple times.

-- 1) Enum type to match app.fee_models.FeeType values
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'fee_type') THEN
    -- SQLAlchemy's default Enum persistence uses Enum *names* (e.g., "GOLF"), not values.
    -- Keep these uppercase to match what the app inserts.
    CREATE TYPE fee_type AS ENUM ('GOLF', 'CART', 'COMPETITION', 'DRIVING_RANGE', 'OTHER');
  END IF;
END $$;

-- 2) Table
CREATE TABLE IF NOT EXISTS public.fee_categories (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code integer NOT NULL UNIQUE,
  description varchar(500) NOT NULL,
  price double precision NOT NULL,
  fee_type fee_type NOT NULL DEFAULT 'GOLF',
  active integer NOT NULL DEFAULT 1,

  -- Optional filters for auto-pricing
  audience varchar(30) NULL,
  gender varchar(10) NULL,
  day_kind varchar(10) NULL,
  weekday smallint NULL,
  holes smallint NULL,
  min_age integer NULL,
  max_age integer NULL,
  priority integer NOT NULL DEFAULT 0
);

-- 3) Ensure columns exist (if table pre-existed)
ALTER TABLE public.fee_categories ADD COLUMN IF NOT EXISTS audience varchar(30) NULL;
ALTER TABLE public.fee_categories ADD COLUMN IF NOT EXISTS gender varchar(10) NULL;
ALTER TABLE public.fee_categories ADD COLUMN IF NOT EXISTS day_kind varchar(10) NULL;
ALTER TABLE public.fee_categories ADD COLUMN IF NOT EXISTS weekday smallint NULL;
ALTER TABLE public.fee_categories ADD COLUMN IF NOT EXISTS holes smallint NULL;
ALTER TABLE public.fee_categories ADD COLUMN IF NOT EXISTS min_age integer NULL;
ALTER TABLE public.fee_categories ADD COLUMN IF NOT EXISTS max_age integer NULL;
ALTER TABLE public.fee_categories ADD COLUMN IF NOT EXISTS priority integer NOT NULL DEFAULT 0;

-- 4) Indexes
CREATE INDEX IF NOT EXISTS idx_fee_categories_code ON public.fee_categories (code);
CREATE INDEX IF NOT EXISTS idx_fee_categories_fee_type ON public.fee_categories (fee_type);
CREATE INDEX IF NOT EXISTS idx_fee_categories_audience ON public.fee_categories (audience);
CREATE INDEX IF NOT EXISTS idx_fee_categories_day_kind ON public.fee_categories (day_kind);
CREATE INDEX IF NOT EXISTS idx_fee_categories_weekday ON public.fee_categories (weekday);
CREATE INDEX IF NOT EXISTS idx_fee_categories_holes ON public.fee_categories (holes);
CREATE INDEX IF NOT EXISTS idx_fee_categories_gender ON public.fee_categories (gender);
CREATE INDEX IF NOT EXISTS idx_fee_categories_min_age ON public.fee_categories (min_age);
CREATE INDEX IF NOT EXISTS idx_fee_categories_max_age ON public.fee_categories (max_age);
CREATE INDEX IF NOT EXISTS idx_fee_categories_priority ON public.fee_categories (priority);

-- 5) Optional: link bookings.fee_category_id if bookings table exists
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name = 'bookings'
  ) THEN
    ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS fee_category_id integer NULL;

    IF NOT EXISTS (
      SELECT 1
      FROM pg_constraint
      WHERE conname = 'fk_bookings_fee_category_id'
    ) THEN
      ALTER TABLE public.bookings
        ADD CONSTRAINT fk_bookings_fee_category_id
        FOREIGN KEY (fee_category_id) REFERENCES public.fee_categories(id);
    END IF;
  END IF;
END $$;
